// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SWE632SeleniumTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sWE632SeleniumTest() {
    driver.get("http://mason.gmu.edu/~kdonapat/");
    driver.manage().window().setSize(new Dimension(1297, 912));
    driver.findElement(By.id("student-id")).click();
    driver.findElement(By.id("student-id")).sendKeys("kdonapat@gmu.edu");
    driver.findElement(By.cssSelector(".mb-3:nth-child(2)")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Kruthay1");
    driver.findElement(By.id("submit-btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("The credentials entered are incorrect"));
    driver.findElement(By.id("student-id")).click();
    driver.findElement(By.id("student-id")).sendKeys("kdonapa");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("afdasf");
    driver.findElement(By.id("submit-btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("This account does not exists"));
    driver.findElement(By.id("student-id")).click();
    driver.findElement(By.id("student-id")).sendKeys("kdonapat@gmu.edu");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Kruthay1!");
    driver.findElement(By.id("submit-btn")).click();
    driver.findElement(By.cssSelector(".card-body:nth-child(1) .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".card-body:nth-child(1) .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#course1 .btn")).click();
    driver.findElement(By.cssSelector(".card-body:nth-child(2) .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".card-body:nth-child(2) .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#course2 span")).click();
    driver.findElement(By.cssSelector(".card-body:nth-child(3) .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".card-body:nth-child(3) .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".modal-dialog-centered .btn")).click();
    driver.findElement(By.id("course-prof-2")).click();
    driver.findElement(By.linkText("Registration")).click();
    driver.findElement(By.cssSelector("select:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = 'Summer-2023']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = 'Fall-2023']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = 'Spring 2023']")).click();
    }
    driver.findElement(By.cssSelector(".groupOfForm:nth-child(2) > .close:nth-child(2) > input")).click();
    driver.findElement(By.id("department")).click();
    driver.findElement(By.id("department")).sendKeys("Data Analytics");
    driver.findElement(By.name("department")).click();
    driver.findElement(By.id("dcode")).click();
    driver.findElement(By.id("department")).click();
    driver.findElement(By.id("department")).click();
    driver.findElement(By.cssSelector(".groupOfInput > .groupOfForm")).click();
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("dcode")).click();
    driver.findElement(By.id("dcode")).sendKeys("CS");
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("cno")).click();
    driver.findElement(By.id("cno")).sendKeys("583");
    driver.findElement(By.id("advanced-option")).click();
    driver.findElement(By.cssSelector(".groupOfForm:nth-child(1) > .close:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector(".close:nth-child(4) > input")).click();
    driver.findElement(By.id("cName")).click();
    driver.findElement(By.cssSelector("label > #cName")).click();
    driver.findElement(By.xpath("(//input[@id=\'cb\'])[2]")).click();
    driver.findElement(By.id("cb")).click();
    driver.findElement(By.id("search-btn")).click();
    driver.findElement(By.id("add-class")).click();
    driver.findElement(By.id("cno")).click();
    driver.findElement(By.id("cno")).sendKeys("58321");
    driver.findElement(By.id("search-btn")).click();
    driver.findElement(By.cssSelector(".groupOfForm:nth-child(3) > .close:nth-child(2)")).click();
    driver.findElement(By.id("dcode")).click();
    driver.findElement(By.id("row21")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.id("student-id")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.close();
  }
}
